x-logs: &logs
    logging:
        driver: json-file
        options:
            max-size: "1m"
            max-file: "5"
            compress: "false"

x-ulimits: &ulimits
    ulimits:
        nofile:
            soft: 2048
            hard: 32000

x-sysctls: &sysctls
    # net.core.default_qdisc: fq
    # net.core.rmem_max: 2097152
    # net.core.wmem_max: 2097152
    # net.core.netdev_max_backlog: 8192
    net.core.somaxconn: 8192
    net.ipv4.udp_rmem_min: 8192
    net.ipv4.udp_wmem_min: 8192
    net.ipv4.tcp_fastopen: 3
    net.ipv4.tcp_keepalive_time: 3600
    net.ipv4.tcp_slow_start_after_idle: 0
    net.ipv4.tcp_congestion_control: bbr

    # Enable IP spoof protection
    net.ipv4.conf.all.rp_filter: 1

    # Disable ICMP redirect messages
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.conf.all.accept_source_route: 0

    # Disable IP source routing
    net.ipv6.conf.all.accept_redirects: 0
    net.ipv6.conf.all.accept_source_route: 0

x-common: &common
    restart: always
    <<: [*logs, *ulimits]
    sysctls:
        <<: *sysctls

volumes:
    temp:

networks:
    general:
        driver: bridge
        enable_ipv6: ${ENABLE_IPV6:-false}
        ipam:
            config:
                - subnet: 192.168.100.0/28
                - subnet: ${IPV6_SUBNET:-::/128}

secrets:
    cloudflare_api_token:
        environment: CLOUDFLARE_API_TOKEN
    ocserv_key:
        environment: OCSERV_KEY
    api_key:
        environment: API_KEY

services:
    bypasshub:
        build: ./bypasshub
        volumes:
            - ./bypasshub:/usr/local/src/bypasshub/bypasshub:ro
            - ./bypasshub/database:/var/lib/bypasshub
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.2
                ipv6_address: $BYPASSHUB_IPV6
        depends_on:
            certbot:
                condition: service_healthy
        secrets:
            - api_key
        profiles:
            - default
        environment:
            DOMAIN: $DOMAIN
            ENABLE_XRAY_CDN: $ENABLE_XRAY_CDN
            ENABLE_XRAY_SUBSCRIPTION: $ENABLE_XRAY_SUBSCRIPTION
            ENABLE_API: $ENABLE_API
            ENABLE_API_UI: $ENABLE_API_UI
            XRAY_SNI: $XRAY_SNI
            XRAY_CDN_SNI: $XRAY_CDN_SNI
            TLS_PORT: $TLS_PORT
            CDN_TLS_PORT: $CDN_TLS_PORT
            COMPOSE_PROFILES: ${COMPOSE_PROFILES:?}
        stop_grace_period: 20s
        <<: *common

    bind:
        build: ./bind
        volumes:
            - ./bind/named.conf:/etc/bind/named.conf:ro
            - ./bind/db.forward:/etc/bind/db.forward:ro
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.3
                ipv6_address: $BIND_IPV6
        cap_add:
            - NET_ADMIN # for iptables
        profiles:
            - default
        environment:
            DOMAIN: ${DOMAIN:?}
            XRAY_SNI: $XRAY_SNI
            OCSERV_SNI: $OCSERV_SNI
            ENABLE_DNSSEC: $ENABLE_DNSSEC
            DNS_CACHE_SIZE: ${DNS_CACHE_SIZE:?}
            DNS_IPV4: ${DNS_IPV4:?}
            DNS_IPV6: $DNS_IPV6
            PUBLIC_IPV4: $PUBLIC_IPV4
            ENABLE_IPV6: $ENABLE_IPV6
            IPV6_SUBNET: $IPV6_SUBNET
            BIND_IPV6: $BIND_IPV6
            NGINX_IPV6: $NGINX_IPV6
            COMPOSE_PROFILES: ${COMPOSE_PROFILES:?}
        <<: *common

    certbot:
        build:
            context: ./certbot
            args:
                PLUGIN: cloudflare
        volumes:
            - ./certbot/letsencrypt:/etc/letsencrypt
            - ./certbot/letsencrypt/lib:/var/lib/letsencrypt
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.4
                ipv6_address: $CERTBOT_IPV6
        secrets:
            - cloudflare_api_token
        profiles:
            - default
        environment:
            DOMAIN: ${DOMAIN:?}
            XRAY_SNI: $XRAY_SNI
            XRAY_CDN_SNI: $XRAY_CDN_SNI
            OCSERV_SNI: $OCSERV_SNI
            EMAIL: $EMAIL
            ENABLE_AUTHORITATIVE_ZONE: $ENABLE_AUTHORITATIVE_ZONE
            ENABLE_CERTBOT_HTTP_MODE: $ENABLE_CERTBOT_HTTP_MODE
            ENABLE_IPV6: $ENABLE_IPV6
            CERTBOT_RENEWAL_LEFT_DAYS: $CERTBOT_RENEWAL_LEFT_DAYS
            BIND_IPV4: 192.168.100.3
        restart: on-failure:1

    nginx:
        build: ./nginx
        volumes:
            - ./nginx/static:/etc/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certbot/letsencrypt/live/$DOMAIN:/etc/letsencrypt/live/$DOMAIN:ro
            - ./certbot/letsencrypt/archive/$DOMAIN:/etc/letsencrypt/archive/$DOMAIN:ro
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.5
                ipv6_address: $NGINX_IPV6
        cap_add:
            - NET_ADMIN # for iptables
        ports:
            - ${TLS_PORT:?}:443/tcp
        depends_on:
            certbot:
                condition: service_healthy
        profiles:
            - default
        environment:
            DOMAIN: ${DOMAIN:?}
            XRAY_SNI: $XRAY_SNI
            XRAY_CDN_SNI: $XRAY_CDN_SNI
            OCSERV_SNI: $OCSERV_SNI
            OCSERV_DTLS_PORT: $OCSERV_DTLS_PORT
            TLS_PORT: ${TLS_PORT:?}
            ENABLE_IPV6: $ENABLE_IPV6
            IPV6_SUBNET: $IPV6_SUBNET
            CERTBOT_IPV4: 192.168.100.4
            CERTBOT_IPV6: $CERTBOT_IPV6
            NGINX_IPV4: 192.168.100.5
            NGINX_IPV6: $NGINX_IPV6
            OCSERV_IPV4: 192.168.100.7
            NGINX_LOG_PURGE_INTERVAL: $NGINX_LOG_PURGE_INTERVAL
            COMPOSE_PROFILES: ${COMPOSE_PROFILES:?}
        <<: *common

    xray:
        build: ./xray
        volumes:
            - ./xray/configs:/usr/local/etc/xray/confs:ro
            - ./xray/xray.json:/usr/local/etc/xray/xray.json:ro
            - ./certbot/letsencrypt/live/$DOMAIN:/etc/letsencrypt/live/$DOMAIN:ro
            - ./certbot/letsencrypt/archive/$DOMAIN:/etc/letsencrypt/archive/$DOMAIN:ro
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.6
                ipv6_address: $XRAY_IPV6
        cap_add:
            - NET_ADMIN # for iptables
        depends_on:
            - bypasshub
            - bind
        profiles:
            - xray
        environment:
            DOMAIN: $DOMAIN
            TLS_PORT: $TLS_PORT
            ENABLE_XRAY_CDN: $ENABLE_XRAY_CDN
            ENABLE_XRAY_SUBSCRIPTION: $ENABLE_XRAY_SUBSCRIPTION
            ENABLE_IPV6: $ENABLE_IPV6
            IPV6_SUBNET: $IPV6_SUBNET
            BIND_IPV4: 192.168.100.3
            BIND_IPV6: $BIND_IPV6
            NGINX_IPV6: $NGINX_IPV6
        <<: *common

    ocserv:
        build: ./ocserv
        volumes:
            - ./ocserv/configs:/etc/ocserv/configs:ro
            - ./ocserv/ocserv.conf:/etc/ocserv/ocserv.conf:ro
            - ./certbot/letsencrypt/live/$DOMAIN:/etc/letsencrypt/live/$DOMAIN:ro
            - ./certbot/letsencrypt/archive/$DOMAIN:/etc/letsencrypt/archive/$DOMAIN:ro
            - temp:/tmp
        networks:
            general:
                ipv4_address: 192.168.100.7
                ipv6_address: $OCSERV_IPV6
        cap_add:
            - NET_ADMIN
            - CAP_MKNOD
        depends_on:
            - bypasshub
            - bind
        secrets:
            - ocserv_key
        profiles:
            - ocserv
        sysctls:
            <<: *sysctls
            net.ipv4.ip_forward: 1
            net.ipv6.conf.all.forwarding: 1
            net.ipv6.conf.all.proxy_ndp: 1
            net.ipv6.conf.all.disable_ipv6: 0
        environment:
            DOMAIN: $DOMAIN
            TLS_PORT: $TLS_PORT
            OCSERV_DTLS_PORT: $OCSERV_DTLS_PORT
            ENABLE_IPV6: $ENABLE_IPV6
            IPV6_SUBNET: $IPV6_SUBNET
            OCSERV_IPV4_SUBNET: $OCSERV_IPV4_SUBNET
            OCSERV_IPV6_SUBNET: $OCSERV_IPV6_SUBNET
            OCSERV_CLIENTS_IPV6_CIDR: $OCSERV_CLIENTS_IPV6_CIDR
            BIND_IPV4: 192.168.100.3
            BIND_IPV6: $BIND_IPV6
            NGINX_IPV4: 192.168.100.5
            NGINX_IPV6: $NGINX_IPV6
            OCSERV_IPV4: 192.168.100.7
        restart: always
        <<: [*logs, *ulimits]
