services:
    nginx:
        ports:
            - 80:80/tcp
        depends_on:
            certbot:
                condition: service_started
        environment:
            ENABLE_CERTBOT_HTTP_MODE: $ENABLE_CERTBOT_HTTP_MODE
